turntable_with_model:
  type: mesh
  file_name: package://acoustic_measurement/config/environments/turntable_with_model.stl
  pose:
    x: 0.7
    y: 0.25
    z: -0.73
    rx: 1.57
    ry: 0.0
    rz: 0.0
  collisions: true
  robot_base_collisions: false
